Добавлен новый класс Режиссеры.
kafi40/java-filmorate pull request #22
Opened 2024-09-05 10:50 UTC by D1R3kT

Добавлена функциональность поиска фильмов по режиссеру.

2024-09-05 17:56 UTC, kafi40 commented
Сделай update для ветки develop, а то конфликты полезут т.к. уже два мержа было в develop

2024-09-05 18:50 UTC, 1EVILGUN1 approved these changes

2024-09-05 18:50 UTC, 1EVILGUN1 commented on src/main/resources/schema.sql
> +    film_id INTEGER NOT NULL REFERENCES "film" (id),
Добавь чтоб каскадно все удалялось при удалении фильма id фильма останется
film_id INTEGER NOT NULL REFERENCES "film" (id)
ON DELETE CASCADE ON UPDATE CASCADE,
director_id INTEGER NOT NULL REFERENCES "director" (id)
ON DELETE CASCADE ON UPDATE CASCADE

2024-09-06 07:21 UTC, kafi40 requested changes

2024-09-06 07:21 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +}
Привет, было бы отлично если контроллер возвращал DirectorDto. Возвращать саму сущность плохая практика, как и Optinal. Создай мапперы для преобразования по аналогии с имеющимся. Также на request было бы хорошо, чтоб приходил DirectorRequest.

2024-09-06 07:21 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    private final DirectorService service;
Тут можно вместо service, сделать directorService. Вдруг еще какие то сервисы добавляться буду

2024-09-06 07:21 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/storage/mappers/FilmRowMapper.java
>      }
Можно добавить аннотацию @RequiredArgsConstructor, будет компактнее

2024-09-06 07:21 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +
Опять же встает вопрос стиля написания запросов

2024-09-06 07:21 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +}
Сервису лучше не возвращать сущность, лучше вернуть Dto через маппер

2024-09-06 07:21 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/dto/director/DirectorFromFilmRequest.java
> +}
Можно переименовать в DirectorRequest )) Я тогда плохо назвал класс

2024-09-07 13:45 UTC, FalseTheory requested changes

2024-09-07 13:45 UTC, FalseTheory commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> -    private static final String FIND_TOP_FILMS =
Запрос TOP_FILMS никак тут не изменился, а мы решили придерживаться стиля, который предлагает IDEA.

2024-09-07 13:45 UTC, FalseTheory commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS "director" CASCADE;
Названия новых таблиц можно сделать во множественном числе.

2024-09-09 10:08 UTC, kafi40 commented
Отлично

2024-09-09 10:08 UTC, kafi40 approved these changes

2024-09-09 10:29 UTC, FalseTheory approved these changes

2024-09-09 10:31 UTC, merged