Add reviews
kafi40/java-filmorate pull request #32
Opened 2024-09-09 13:02 UTC by kafi40

Добавлена фича отзывов. Проведен рефакторинг кода и классов. Оптимизирован код

2024-09-09 17:01 UTC, FalseTheory requested changes

2024-09-09 17:01 UTC, FalseTheory commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
>  @RequiredArgsConstructor
Можно оставить directorService интерфейс, реализация подтянется и не придется все наименования рефакторить

2024-09-09 17:01 UTC, FalseTheory commented on src/main/java/ru/yandex/practicum/filmorate/controller/model/review/ReviewRequest.java
> +    private Boolean isPositive;
Можно добавить сообщение ошибки при нарушении условия NotBlank

2024-09-09 17:01 UTC, FalseTheory commented on src/main/java/ru/yandex/practicum/filmorate/repository/RatingRepository.java
> -public interface RatingStorage {
Тут тоже можно тоже имплементировать Repository

2024-09-09 17:01 UTC, FalseTheory commented on src/main/java/ru/yandex/practicum/filmorate/repository/Repository.java
> +package ru.yandex.practicum.filmorate.repository;
Как будто бы излишняя декомпозиция получается, все случаи где используется этот интерфейс всё равно по новой объявляют метод get. (Можно сделать Generic интерфейс, не через ?)

2024-09-09 18:22 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/repository/Repository.java
> +package ru.yandex.practicum.filmorate.repository;
Тут надо обратить внимание, что метод checkId вынесен в утилитарный класс, в который передается репозиторий и массив id. Тут используется WildCard, потому что не важно какой репозиторий мы передадим, главное, что он имеет метод get. Наоборот с generic пришлось бы указывать родительский класс для сущностей и вместо ? указать родителя

2024-09-09 18:26 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/repository/RatingRepository.java
> -public interface RatingStorage {
Как раз к последующему комменту. Если нам потребуется проверить существование рейтинга с каким то id, будет достаточно имплементировать Repository и вызвать метод checkId из утилитарного класс. Просто в коде нигде не было проверки, а так да, можно добавить.

2024-09-09 18:26 UTC, kafi40 commented on src/main/java/ru/yandex/practicum/filmorate/controller/model/review/ReviewRequest.java
> +    private Boolean isPositive;
Согласен, добавлю

2024-09-10 09:57 UTC, 1EVILGUN1 approved these changes

2024-09-10 10:32 UTC, D1R3kT approved these changes

2024-09-10 14:22 UTC, FalseTheory approved these changes

2024-09-10 16:16 UTC, closed without merging